version: 0.2

env:
  #secrets-manager:
    #SONAR_TOKEN: "sonarqube:sonartoken"
    SONAR_TOKEN: "7c3896c62913eda8b5e99f7c41b80a7cc28f50a7"

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y openjdk-17-jdk wget jq
      - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH

  build:
    commands:
      - echo "Running Maven build and SonarQube analysis..."
      - mvn verify sonar:sonar -Dsonar.projectKey=somanaboina-522_devsecops -Dsonar.organization=somanaboina-522 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
